LibraryManagement/Pages/Application/AdminArea/AccountManagement/Index.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace LibraryManagement.Pages.Application.AdminArea.AccountManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IBaseRepository<IdentityUser> _accountRepo;
        public IndexModel(UserManager<IdentityUser> userManager,
                          IBaseRepository<IdentityUser> accountRepo,
                          SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _accountRepo = accountRepo;
            _signInManager = signInManager;
        }
        [BindProperty]
        public DeleteAccountInputModel DelAccInput { get; set; }
        public bool RequirePassword { get; set; }
        [BindProperty]
        public AddSubAdminAccountInputModel AddSubAdminInput { get; set; }
        public List<IdentityUser> Accounts { get; set; }

        public async Task OnGetAsync()
        {
            var accounts = await _accountRepo.GetAllRecords();
            Accounts = accounts.Where(x => x.UserName != User.Identity?.Name).ToList();
        }
        public async Task<IActionResult> OnPostAddAdmin()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var account = new IdentityUser()
            {
                EmailConfirmed = true,
                Email = AddSubAdminInput.Email,
                UserName = AddSubAdminInput.Email,
            };
            var create = await _userManager.CreateAsync(account, AddSubAdminInput.Password);
            if (!create.Succeeded)
            {

                TempData["ValidationMessage"] = "can't add this account (make sure that you used unique email)";
                return RedirectToPage();
            }
            TempData["ValidationMessage"] = "successfully added";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostDeleteAcc()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            RequirePassword = await _userManager.HasPasswordAsync(user);
            if (RequirePassword)
            {
                if (!await _userManager.CheckPasswordAsync(user, DelAccInput.Password))
                {
                    TempData["ValidationMessage"] = "incorrect password";
                    return RedirectToPage();
                }
            }

            var result = await _userManager.DeleteAsync(user);
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Unexpected error occurred deleting user.");
            }
            await _signInManager.SignOutAsync();
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BestUser/Index.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BestUser
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IUserRepository _userRepo;
        public IndexModel(IUserRepository userRepo)
        {
            _userRepo = userRepo;
        }
        public List<BestUserModel> BestUsers { get; set; }
        public User TopOne { get; set; }
        public async Task OnGetAsync()
        {
            var rankingHolder = new List<BestUserModel>();
            var bestUsers = await _userRepo.BestUserRanking();
            var bestUserRank = bestUsers.ToList();
            var topTen = bestUserRank.Count()<=10?bestUserRank.Count():10;
            for(int x = 0; x < topTen; x++)
            {
                rankingHolder.Add(bestUserRank[x]);
            }
            BestUsers = rankingHolder;
            TopOne = await _userRepo.GetOneRecord(rankingHolder.First().UserId);
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BookCategoryManagement/CategoryManagement.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BookCategoryManagement
{
    public class CategoryManagementModel : AdminBasePageModel<BookCategory,InputBookCategoryModel>
    {

        private readonly IBookCategoryRepository _bookCategoryRepo;
        private readonly IMapper _mapper;
        public CategoryManagementModel(IMapper mapper,IBookCategoryRepository bookCategoryRepo):base(bookCategoryRepo,mapper)
        {
            _bookCategoryRepo= bookCategoryRepo;
            _mapper = mapper;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<BookCategory>(InputModel);
            await _bookCategoryRepo.Add(converted);
            validationMess = "successfully added";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostUpdate()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<BookCategory>(InputModel);
            await _bookCategoryRepo.Update(converted.Id,converted);
            validationMess = "successfully updated";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDeleteIntId(int Id)
        {
            if (Id < 0)
                return BadRequest(Id);
            await _bookCategoryRepo.Delete(Id);
            validationMess = "successfully deleted";
            return RedirectToPage();
        }

    }
}

LibraryManagement/Pages/Application/AdminArea/BookCategoryManagement/Index.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BookCategoryManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IBaseRepository<Book> _bookRepo;
        private readonly IBaseRepository<BookCategory> _bCateg;
        private readonly IMapper _mapper;
        public IndexModel(IBaseRepository<Book> bookRepo,IBaseRepository<BookCategory> bCateg,IMapper mapper)
        {
            _bookRepo = bookRepo;
            _bCateg = bCateg;
            _mapper = mapper;
        }


        public List<BookViewModel> Books { get; set; }

        [BindProperty]
        public InputBookModel InputBook { get; set; }
        public async Task OnGetAsync()
        {
            var books = await _bookRepo.GetAllRecords();
            var bCategs = await _bCateg.GetAllRecords();
            var recordBooks = bCategs
                .Join(books,
                bCat => bCat.Id,
                book => book.BookCategoryId,
                (bCat, book) => new BookViewModel
                {
                    Category = bCat,
                    Book = book
                }).ToList();
            Books =  recordBooks;
        }
        public async Task<IActionResult>OnPostAsync()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<Book>(InputBook);
            await _bookRepo.Add(converted);
            TempData["ValidationMessage"] = "successfully added";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostUpdate()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<Book>(InputBook);
            await _bookRepo.Update(converted.Id.ToString(),converted);
            TempData["ValidationMessage"] = "successfully updated";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDeleteIntId(int Id)
        {
            if (Id < 0)
                return NotFound();
            await _bookRepo.Delete(Id.ToString());
            TempData["ValidationMessage"] = "successfully deleted";
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BorrowedBookManagement/Index.cshtml.cs
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BorrowedBookManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IBorrowBookRepository _borBookRepo;
        public IndexModel(IBorrowBookRepository borBookRepo)
        {
            _borBookRepo = borBookRepo;
        }
        public List<BorrowedBooksViewModel> BorrowBookRecord { get; set; }
        public async Task OnGetAsync()
        {
            var borrowBooks = await _borBookRepo.BorrowBookList();
            BorrowBookRecord = borrowBooks.OrderByDescending(x => x.BorrowBook.Id).ToList();
        }
        public async Task<IActionResult> OnGetBookReturn(int Id)
        {
            var borBook = await _borBookRepo.GetOneRecord(Id);
            if (borBook == null)
                return BadRequest("invalid id");
            borBook.Returned = DateTime.Now;
            var result = borBook;
            await _borBookRepo.Update(Id, borBook);
            TempData["ValidationMessage"] = "successfully returned";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnGetDeleteIntId(int Id)
        {
            if(Id<0)
                return NotFound();
            await _borBookRepo.Delete(Id);
            TempData["ValidationMessage"] = "successfully deleted";
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/EmployeeAttendance/Index.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.Infrastracture.Implementations;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Globalization;

namespace LibraryManagement.Pages.Application.AdminArea.EmployeeAttendance
{
    [Authorize]
    public class EmpAttendanceInputModel
    {
        public int Year { get; set; }
        public MonthsInYear Month { get; set; }
        public WeeksInMonth Week { get; set; }
    }
    public class IndexModel : PageModel
    {
        private readonly IEmployeeAttendanceRepository _empRepo;
        public IndexModel(IEmployeeAttendanceRepository empRepo)
        {
            _empRepo = empRepo;
        }
        public List<int> Years { get; set; }

        [TempData]
        public int Year { get; set; }
        [TempData]
        public int Month { get; set; }
        [TempData]
        public WeeksInMonth Week { get; set; }

        [BindProperty]
        public EmpAttendanceInputModel InputModel { get; set; }
        public List<AttendanceThisWeek> AttendanceThisWeek { get; set; }
        public async Task OnGetAsync()
        {
            Years = await _empRepo.Year2019ToNow();
            IEnumerable<AttendanceThisWeek> attWeek;
            if (Year != 0 && Month != 0 && Week != null)
            {
                attWeek = await _empRepo.EmpAttendancePerWeek(new DateTime(Year,Month,1),Week);
                InputModel = new EmpAttendanceInputModel
                {
                    Year = Year,
                    Month = (MonthsInYear)Month,
                    Week = Week
                };
            }
            else
            {
                CultureInfo ci = CultureInfo.CurrentCulture;
                Calendar calendar = ci.Calendar;
                int weekNumberInMonth = calendar.GetWeekOfYear(DateTime.Now, CalendarWeekRule.FirstDay, DayOfWeek.Sunday) -
                calendar.GetWeekOfYear(DateTime.Now.AddDays(1 - DateTime.Now.Day), CalendarWeekRule.FirstDay, DayOfWeek.Sunday) + 1;
                attWeek = await _empRepo.EmpAttendancePerWeek(null,(WeeksInMonth)weekNumberInMonth-2);
                InputModel = new EmpAttendanceInputModel
                {
                    Year = DateTime.Now.Year,
                    Month = (MonthsInYear)(DateTime.Now.Month),
                    Week = (WeeksInMonth)weekNumberInMonth - 2
                };
            }
            AttendanceThisWeek= attWeek.ToList();
        }
        public async Task<IActionResult> OnPostFilterAttendance()
        {
 
            Year = InputModel.Year;
            Month = (int)InputModel.Month;
            Week = InputModel.Week;
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/FacultyManagement.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;

namespace LibraryManagement.Pages.Application.AdminArea.UserManagement
{
    public class FacultyManagementModel: UserManagementBasePageModel<User,InputUserModel>
    {
        public FacultyManagementModel(IUserRepository userRepo, IMapper map) : base(userRepo, map)
        {
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/GuestManagement.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.UserManagement
{
    public class GuestManagementModel : UserManagementBasePageModel<User,InputUserModel>
    {
       public GuestManagementModel(IUserRepository repo,IMapper mapp):base(repo,mapp) { }
    }
}

LibraryManagement/Pages/ViewComponents/DashboardNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public class DashboardNavigationViewComponent: ViewComponent
    {
        public DashboardNavigationViewComponent() { }
        public async Task<IViewComponentResult> InvokeAsync(DNVModel model)
        {
            return View(model);
        }
    }
    public class DNVModel
    {
        public string PageName { get; set; }
        public (string linkName,string pageName,bool isCurrentPage)[] LinkName { get; set;}
    }
}

LibraryManagement/Pages/ViewComponents/UpdateBookCategoryViewComponent.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public class UpdateBookCategoryViewComponent: ViewComponent
    {
        private readonly IBookCategoryRepository _bookCategoryRepo;
        private readonly IMapper _mapper;
        public UpdateBookCategoryViewComponent(IMapper mapper,IBookCategoryRepository bookCategoryRepo)
        {
            _mapper = mapper;
            _bookCategoryRepo = bookCategoryRepo;
        }
        public async Task<IViewComponentResult> InvokeAsync(int Id)
        {
            var bookCategory = await _bookCategoryRepo.GetOne(Id);
            var converted = _mapper.Map<InputBookCategoryModel>(bookCategory);
            return View(converted);
        }
    }
}

LibraryManagement/Pages/ViewComponents/UpdateBookViewComponent.cs
using AutoMapper;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public class UpdateBookViewComponent:ViewComponent
    {
        private readonly IBookRepository _bookRepo;
        private readonly IMapper _mapper;
        public UpdateBookViewComponent(IBookRepository bookRepo,IMapper mapper)
        {
            _bookRepo = bookRepo;
            _mapper = mapper;
        }
        public async Task<IViewComponentResult> InvokeAsync(int Id)
        {
            var book = await _bookRepo.GetOneBook(Id);
            var converted = _mapper.Map<InputBookModel>(book);
            return View(converted);
        }

    }
}

LibraryManagement/Pages/Application/AdminArea/BookCategoryManagement/CategoryManagement.cshtml
@page
@model LibraryManagement.Pages.Application.AdminArea.BookCategoryManagement.CategoryManagementModel
@{
    var bcVal = new DNVModel
            {
                PageName = "Book Category",
                LinkName = new (string linkName, string pageName, bool isCurrentPage)[]
                                        {
            ("/Application/AdminArea/Index","Dashboard",false),
             ("./Index","Book Management",false),
            (null,"Book Category Management",true)
                                        }
            };
    ViewData["Title"] = "Book Category";
}
<vc:dashboard-navigation model="bcVal" />
<partial name="PartialViews/_ValidationMessage" />
<div class="d-flex align-items-center justify-content-between mb-2">
    <button data-bs-target="#bookCategoryModalAdd" data-bs-toggle="modal" class="btn btn-primary rounded-pill px-4">Add New Category <i class="fa-solid fa-plus"></i></button>
    <partial name="_AddBookCategory" model="new InputBookCategoryModel()"/>
    
</div>
<div class=" bg-white rounded-3 shadow px-4 py-3">
    <table id="exportTable"
           data-toggle="table"
           data-search="true"
           data-pagination="true"
           data-side-pagination="client"
           data-page-size="5"
           data-page-list="[5,10,25,50,100,All]">
        <thead>
            <tr>
                <th data-sortable="true">Id</th>
                <th data-sortable="true">Category Name</th>
                <th data-sortable="true">AddedAt/UpdateAt</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach(var bookrecord in Model.Records)
            {
                <tr>
                    <td>@bookrecord.Id</td>
                    <td>@bookrecord.CategoryName</td>
                    <td>@bookrecord.AddedAt.ToString("yyy/MM/dd") <b>-</b> @bookrecord.LastUpdatedAt.ToString("yyy/MM/dd")</td>
                    <td>
                        <div class="text-nowrap">
                            <button type="button" data-bs-toggle="modal" data-bs-target="#bookCategoryUpdateModal_@(bookrecord.Id)" class="btn btn-success rounded-4 "><i class="fa-solid fa-pen-to-square"></i></button>
                            <vc:update-book-category Id="bookrecord.Id"/>
                            <button type="button" data-bs-toggle="modal" data-bs-target="#deleteModal_@(bookrecord.Id)" class="btn btn-danger rounded-4"><i class="fa-solid fa-trash-can"></i></button>
                            <partial name="PartialViews/_DeleteRecIdInt" model="bookrecord.Id" />
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts {
    <partial name="PartialViews/_ValidationScriptsPartial" />

}

LibraryManagement/Pages/Application/AdminArea/BookCategoryManagement/Index.cshtml
@page
@model LibraryManagement.Pages.Application.AdminArea.BookCategoryManagement.IndexModel
@{
    var bcVal = new DNVModel
            {
                PageName = "Book",
                LinkName = new (string linkName, string pageName, bool isCurrentPage)[]
                                                    {
            ("/Application/AdminArea/Index","Dashboard",false),
            (null,"Book Management",true)
                                                    }
            };
    ViewData["Title"] = "Book";
}
<vc:dashboard-navigation model="bcVal"/>
<partial name="PartialViews/_ValidationMessage" />
<div class="d-flex align-items-center justify-content-between mb-2">
    <div class="d-flex gap-2">
        <button data-bs-target="#add-book" data-bs-toggle="modal" class="btn btn-primary rounded-pill px-4">Add New Book<i class="fa-solid fa-plus"></i></button>
        <a asp-page="./CategoryManagement" class="btn btn-primary px-5 rounded-pill">Category <i class="fa-solid fa-layer-group"></i></a>
        <partial name="_AddBook" model="new InputBookModel()" />
    </div>
    <button id="btn-export-excel" class="btn btn-info text-white rounded-3"><i class="fa-regular fa-file-excel"></i></button>
</div>
<div class=" bg-white rounded-3 shadow px-4 py-3">
    <table id="exportTable"
        class="table"
           data-toggle="table"
           data-search="true"
           data-pagination="true"
           data-side-pagination="client"
           data-page-size="5"
           data-page-list="[5,10,25,50,100,All]">
        <thead>
            <tr>
                <th data-sortable="true">Id</th>
                <th data-sortable="true">Title Of the Book</th>
                <th data-sortable="true">Author</th>
                <th data-sortable="true">Book Category</th>
                <th data-sortable="true">Class No</th>
                <th data-sortable="true">Accession No.</th>
                <th data-sortable="true">Edition</th>
                <th data-sortable="true">Volumes</th>
                <th data-sortable="true">Pages</th>
                <th data-sortable="true">Copies</th>
                <th data-sortable="true">Source Of fund</th>
                <th data-sortable="true">Publisher</th>
                <th data-sortable="true">Year</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            @foreach (var bookrecord in Model.Books)
            {
                <tr>
                    <td>@bookrecord.Book.Id</td>
                    <td>@bookrecord.Book.Title</td>
                    <td>@bookrecord.Book.Author</td>
                    <td>@bookrecord.Category.CategoryName</td>
                    <td>@bookrecord.Book.ClassNo</td>
                    <td>@bookrecord.Book.AccessionNumber</td>
                    <td>@bookrecord.Book.Edition</td>
                    <td>@bookrecord.Book.Volume</td>
                    <td>@bookrecord.Book.Pages</td>
                    <td>@bookrecord.Book.Copies</td>
                    <td>@bookrecord.Book.SourceOfFund</td>
                    <td>@bookrecord.Book.Publisher</td>
                    <td>@bookrecord.Book.Year</td>
                    <td>
                        <div class="text-nowrap">
                            <button type="button" data-bs-toggle="modal" data-bs-target="#update-book-@(bookrecord.Book.Id)" class="btn btn-success rounded-4 "><i class="fa-solid fa-pen-to-square"></i></button>
                            <vc:update-book id="bookrecord.Book.Id"/>
                            <button type="button" data-bs-toggle="modal" data-bs-target="#deleteModal_@(bookrecord.Book.Id)" class="btn btn-danger rounded-4"><i class="fa-solid fa-trash-can"></i></button>
                            <partial name="PartialViews/_DeleteRecIdInt" model="bookrecord.Book.Id" />
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts {
    <partial name="PartialViews/_ValidationScriptsPartial" />
    <script src="~/js/table2excel.js" asp-append-version="true"></script>
    <script src="~/js/ExportToExcel.js" asp-append-version="true"></script>
}

LibraryManagement/Pages/Application/AdminArea/BookCategoryManagement/_AddBook.cshtml
@model InputBookModel
@inject IBaseRepository<BookCategory> bCategRepo;
@{

    var bcategories = await bCategRepo.GetAllRecords();
}
<div class="modal fade" data-bs-backdrop="static" id="add-book">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post">
                <div class="modal-header">
                    <h5> Add Book</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Title"></label>
                        <input class="form-control" asp-for="Title" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Author"></label>
                        <input class="form-control" asp-for="Author" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Author"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="ClassNo"></label><span class="text-danger">*</span>
                        <input class="form-control" asp-for="ClassNo" placeholder="enter here.."/>
                        <span class="text-danger" asp-validation-for="ClassNo"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="BookCategoryId"></label><span class="text-danger">*</span>
                        <select class="form-select" asp-for="BookCategoryId" asp-items="@bcategories.Select(x => new SelectListItem(x.CategoryName,x.Id.ToString()))">
                        </select>
                        <span class="text-danger" asp-validation-for="BookCategoryId"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="AccessionNumber"></label>
                        <textarea class="form-control" asp-for="AccessionNumber" placeholder="Enter here..">
                        </textarea>
                        <span class="text-danger" asp-validation-for="AccessionNumber"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Edition"></label>
                        <input class="form-control" asp-for="Edition" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Edition"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Volume"></label>
                        <input class="form-control" asp-for="Volume" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Volume"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Title"></label>
                        <input class="form-control" asp-for="Title" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Title"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Pages"></label>
                        <input type="number" class="form-control" asp-for="Pages" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Copies"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Copies"></label>
                        <input type="number" class="form-control" asp-for="Copies" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Copies"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="SourceOfFund"></label>
                        <input class="form-control" asp-for="SourceOfFund" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="SourceOfFund"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Publisher"></label>
                        <input class="form-control" asp-for="Publisher" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Publisher"></span>
                    </div>
                    <div class="mb-3">
                        <label class="fw-bolder mb-2" asp-for="Year"></label>
                        <input type="number" class="form-control" asp-for="Year" placeholder="enter here.." />
                        <span class="text-danger" asp-validation-for="Year"></span>
                    </div>  

                </div>
                <div class="modal-footer">
                    <button class="btn btn-light" type="reset">Reset</button>
                    <button class="btn btn-primary" type="submit">Add</button>
                </div>
            </form>
        </div>
    </div>
 </div>