LibraryManagement/Pages/Application/AdminArea/AccountManagement/Index.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace LibraryManagement.Pages.Application.AdminArea.AccountManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IBaseRepository<IdentityUser> _accountRepo;
        public IndexModel(UserManager<IdentityUser> userManager,
                          IBaseRepository<IdentityUser> accountRepo,
                          SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _accountRepo = accountRepo;
            _signInManager = signInManager;
        }
        [BindProperty]
        public DeleteAccountInputModel DelAccInput { get; set; }
        public bool RequirePassword { get; set; }
        [BindProperty]
        public AddSubAdminAccountInputModel AddSubAdminInput { get; set; }
        public List<IdentityUser> Accounts { get; set; }

        public async Task OnGetAsync()
        {
            var accounts = await _accountRepo.GetAllRecords();
            Accounts = accounts.Where(x => x.UserName != User.Identity?.Name).ToList();
        }
        public async Task<IActionResult> OnPostAddAdmin()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var account = new IdentityUser()
            {
                EmailConfirmed = true,
                Email = AddSubAdminInput.Email,
                UserName = AddSubAdminInput.Email,
            };
            var create = await _userManager.CreateAsync(account, AddSubAdminInput.Password);
            if (!create.Succeeded)
            {

                TempData["ValidationMessage"] = "can't add this account (make sure that you used unique email)";
                return RedirectToPage();
            }
            TempData["ValidationMessage"] = "successfully added";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostDeleteAcc()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            RequirePassword = await _userManager.HasPasswordAsync(user);
            if (RequirePassword)
            {
                if (!await _userManager.CheckPasswordAsync(user, DelAccInput.Password))
                {
                    TempData["ValidationMessage"] = "incorrect password";
                    return RedirectToPage();
                }
            }

            var result = await _userManager.DeleteAsync(user);
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Unexpected error occurred deleting user.");
            }
            await _signInManager.SignOutAsync();
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BestUser/Index.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BestUser
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IUserRepository _userRepo;
        public IndexModel(IUserRepository userRepo)
        {
            _userRepo = userRepo;
        }
        public List<BestUserModel> BestUsers { get; set; }
        public User TopOne { get; set; }
        public async Task OnGetAsync()
        {
            var rankingHolder = new List<BestUserModel>();
            var bestUsers = await _userRepo.BestUserRanking();
            var bestUserRank = bestUsers.ToList();
            var topTen = bestUserRank.Count()<=10?bestUserRank.Count():10;
            for(int x = 0; x < topTen; x++)
            {
                rankingHolder.Add(bestUserRank[x]);
            }
            BestUsers = rankingHolder;
            TopOne = await _userRepo.GetOneRecord(rankingHolder.First().UserId);
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BorrowedBookManagement/Index.cshtml.cs
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BorrowedBookManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IBorrowBookRepository _borBookRepo;
        public IndexModel(IBorrowBookRepository borBookRepo)
        {
            _borBookRepo = borBookRepo;
        }
        public List<BorrowedBooksViewModel> BorrowBookRecord { get; set; }
        public async Task OnGetAsync()
        {
            var borrowBooks = await _borBookRepo.BorrowBookList();
            BorrowBookRecord = borrowBooks.OrderByDescending(x => x.BorrowBook.Id).ToList();
        }
        public async Task<IActionResult> OnGetBookReturn(int Id)
        {
            var borBook = await _borBookRepo.GetOneRecord(Id);
            if (borBook == null)
                return BadRequest("invalid id");
            borBook.Returned = DateTime.Now;
            var result = borBook;
            await _borBookRepo.Update(Id, borBook);
            TempData["ValidationMessage"] = "successfully returned";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnGetDeleteIntId(int Id)
        {
            if(Id<0)
                return NotFound();
            await _borBookRepo.Delete(Id);
            TempData["ValidationMessage"] = "successfully deleted";
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/FacultyManagement.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;

namespace LibraryManagement.Pages.Application.AdminArea.UserManagement
{
    public class FacultyManagementModel: UserManagementBasePageModel<User,InputUserModel>
    {
        public FacultyManagementModel(IUserRepository userRepo, IMapper map) : base(userRepo, map)
        {
        }
    }
}

LibraryManagement/Pages/Application/UserArea/Borrow.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.UserArea
{
    public class BarrowModel : PageModel
    {
        public readonly IBaseRepository<BorrowedBooks> _barrowBookRepo;
        public readonly IBaseRepository<BookCategory> _bookCategRepo;
        public readonly IBaseRepository<Book> _bookRepo;
        public readonly IMapper _mapper;
        public BarrowModel(IBaseRepository<BorrowedBooks> barrowBookRepo,
                            IBaseRepository<BookCategory> bookCategRepo,
                            IBaseRepository<Book> bookRepo,
                           IMapper mapper)
        {
            _barrowBookRepo= barrowBookRepo;
            _bookCategRepo= bookCategRepo;
            _bookRepo = bookRepo;
            _mapper = mapper;
        }
        [BindProperty]
        public InputBorrowedBooksModel InputModel { get; set; }
        public List<BookCategory> BookCategories { get; set; }

        [BindProperty]
        public int? Categ { get; set; }
        [BindProperty]
        public string? Id { get; set; }

        [TempData]
        public int CategId { get; set; }

        [TempData]
        public string tId { get; set; }
        public List<Book> Books { get; set; }

        public string UserId { get; set; }
        public async Task OnGetAsync(string UserId)
        {
            var bookCategories = await _bookCategRepo.GetAllRecords();
            var books = await _bookRepo.GetAllRecords();
            this.UserId = UserId;
            if(CategId > 0)
            {
                Categ = CategId;
                Id = tId;

                InputModel = new InputBorrowedBooksModel
                {
                    UserId = tId
                };
                Books = books.Where(x => x.BookCategoryId == CategId).ToList();
            }
            else
            {
                Id = UserId;
                var firstCategoryId = bookCategories.First().Id;
                Books = books.Where(x => x.BookCategoryId == firstCategoryId).ToList();
            }
            BookCategories = bookCategories.ToList();

        }

        public async Task<IActionResult> OnPostFCategory()
        {
            CategId = (int)Categ;
            tId = Id;
            var userId = Id;
            return RedirectToPage("Borrow",new {userId});
        }

        public async Task<IActionResult> OnPostAsync()
        {
            
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var books = await _bookRepo.GetAllRecords();
            var book = books.FirstOrDefault(x => x.Title == InputModel.Book);
            
            if(book == null)
            {
                var userId = InputModel.UserId;
                TempData["ValidationMessage"] = "invalid book";
                return RedirectToPage("Borrow", new { userId });
            }
            var bookId = book.Id;
            var values = new BorrowedBooks
            {
                BorrowTime = InputModel.BorrowTime,
                BookId = bookId,
                UserId = InputModel.UserId
            };
            await _barrowBookRepo.Add(values);
            TempData["ValidationMessage"] = "successfully borrowed";
            return RedirectToPage("./Index");
        }
    }
}

LibraryManagement/Pages/Application/UserArea/Index.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.Infrastracture.Implementations;
using LibraryManagement.Model.Infrastracture.Services;
using LibraryManagement.Model.ViewModel;
using LibraryManagement.Pages.Application;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;

namespace LibraryManagement.Pages.StudentArea
{
  
    public class IndexModel : PageModel
    {
        private readonly IMapper _mapper;
        private readonly IUserAttendanceRepository _repoUserAttendance;
        private readonly IBorrowBookRepository _borBookRepo;
        private readonly IHubContext<BaseHub, IBaseHub> _baseHub;
        private readonly IUserRepository _repoUser;
        private readonly IBaseRepository<Book> _repoBook;
        public IndexModel(IUserAttendanceRepository repoAttendanceUser,
                          IMapper mapper,
                          IUserRepository repoUser,
                          IBorrowBookRepository borBookRepo,
                          IHubContext<BaseHub, IBaseHub> baseHub,
                          IBaseRepository<Book> repoBook)
        {
            _mapper = mapper;
            _repoUserAttendance= repoAttendanceUser;
            _borBookRepo= borBookRepo;
            _baseHub = baseHub;
            _repoUser = repoUser;
            _repoBook=repoBook;
        }

        public List<UsersAttendanceViewModel> UsersAttendance { get; set; }
        public List<BorrowedBooksViewModel> BorrowedBooks { get; set; }

        public int Books { get; set; }

        [BindProperty]
        public InputUserAttendanceModel InputModel { get; set; }

        [BindProperty]
        public string? UserId { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
           var userAttendance = await _repoUserAttendance.UserAttendanceList();
           var borBooks = await _borBookRepo.BorrowBookList();
            var books = await _repoBook.GetAllRecords();
            Books = books.Count();
            UsersAttendance = userAttendance
                .Where(x => x.UserLog.TimeIn.Date == DateTime.Now.Date)
                .OrderByDescending(x => x.UserLog.Id)
                .ToList();
            BorrowedBooks = borBooks
                .Where(x => x.BorrowBook.BorrowTime.Date == DateTime.Now.Date)
                .OrderByDescending(x => x.BorrowBook.Id)
                .ToList();
            return Page();
        }
        public async Task<IActionResult> OnGetBookReturn(int Id)
        {
            var borBook = await _borBookRepo.GetOneRecord(Id);
            if (borBook == null)
                return BadRequest("invalid id");
            borBook.Returned = DateTime.Now;
            var result = borBook;
            await _borBookRepo.Update(Id, borBook);
            TempData["ValidationMessage"] = "successfully returned";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostBarrowScan()
        {
            var user = await _repoUser.GetOneRecord(UserId);
            if(user == null)
            {
                TempData["ValidationMessage"] = "invalid qr code/id";
                return RedirectToPage();
            }
            return RedirectToPage("./Borrow", new {UserId});
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            else
            {
                var getCurrentLog = await _repoUser.GetOneRecord(InputModel.User);
                if (getCurrentLog == null)
                {
                    TempData["ValidationMessage"] = "invalid qr code/id";
                    return RedirectToPage();
                }
                else
                {
                    var retreiveData = await _repoUserAttendance.GetCurrentLog(InputModel.User);
                    var usersAttendance = await _repoUserAttendance.GetAllRecords();
                    var countLogToday = usersAttendance.Where(x => x.TimeIn.Date == DateTime.Now.Date).Count();
                    if (retreiveData == null)
                    {
                        var converted = _mapper.Map<UserLog>(InputModel);
                        await _repoUserAttendance.Add(converted);
                        TempData["ValidationMessage"] = $"successfully login";

                    }
                    else
                    {
                        var convertedData = _mapper.Map<UserLog>(InputModel);
                        convertedData.TimeIn = retreiveData.TimeIn;
                        convertedData.TimeOut = DateTime.Now;
                        convertedData.Id = retreiveData.Id;
                        await _repoUserAttendance.Update(retreiveData.Id, convertedData);
                        _baseHub.Clients.All.ReceiveStAttendance(
                            getCurrentLog.FirstName + getCurrentLog.MiddleName + getCurrentLog.LastName,
                            retreiveData.TimeIn.ToString("hh:mm:ss tt"),
                            retreiveData.TimeOut?.ToString("hh:mm:ss tt"),
                            getCurrentLog.UserType.ToString(),
                            countLogToday.ToString());
                        TempData["ValidationMessage"] = "successfully logout";
                    }
                }

            }
            return RedirectToPage();

        }
       
    }
}

LibraryManagement/Pages/ViewComponents/NavigationViewComponent.cs
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public enum CurrentPage
    {
        StudentArea,
        EmployeeArea,
        AdminArea
    } 
    public class NavigationViewComponent: ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(CurrentPage currentPage)
        {
            return View(currentPage);
        }
    }
}

LibraryManagement/Pages/ViewComponents/ViewBorrowBookRecordViewComponent.cs
using LibraryManagement.Model.Infrastracture.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public class ViewBorrowBookRecordViewComponent: ViewComponent
    {
        private readonly IBorrowBookRepository _repo;
        public ViewBorrowBookRecordViewComponent(IBorrowBookRepository repo)
        {
            _repo= repo;
        }
        public async Task<IViewComponentResult> InvokeAsync(int Id)
        {
            var borBooks = await _repo.BorrowBookList();
            var borBook = borBooks.FirstOrDefault(x => x.BorrowBook.Id == Id);
            return View(borBook);
        }
    }
}

LibraryManagement/Pages/Application/UserArea/Borrow.cshtml
@page
@model LibraryManagement.Pages.Application.UserArea.BarrowModel
@{
    ViewData["Title"] = "Borrow";
}
<partial name="PartialViews/_ValidationMessage" />
<partial name="_UserLogForm" model="new InputUserAttendanceModel()" />
<vc:navigation current-page="StudentArea" />
<div class="w-100 d-flex justify-content-center pt-5">
    <div class="w-50 bg-white rounded-3 shadow p-4">
        <h4 class="py-2 rounded-3 text-center bg-primary-subtle-custom fw-bolder text-primary">Fill Up To Borrow</h4>
        <div class="mb-3">
            <label class="mb-2 fw-bolder">Category</label><span class="fw-bolder text-danger">*</span>
            <form id="form-filter" method="post" asp-page-handler="FCategory">
                <select asp-for="Categ" class="form-select" id="category" asp-items="@Model.BookCategories.Select(x => new SelectListItem(x.CategoryName,x.Id.ToString()))">
                </select>
                <input type="hidden" asp-for="Id"/>
            </form>
        </div>
        <form method="post">
            <input type="hidden" asp-for="InputModel.BorrowTime" value="@DateTime.Now"/>
            <input type="hidden" asp-for="InputModel.UserId" value="@Model.UserId"/>
            <div class="mb-3">
                <label asp-for="InputModel.Book" class="mb-2 fw-bolder"></label><span class="fw-bolder text-danger">*</span>
                @if (Model.Books.Count() == 0)
                {
                     <input type="text" class="form-control" list="list-books" id="exampleDataList" placeholder="Type to search..." asp-for="InputModel.Book" disabled>
                }
                else
                {
                    <input type="text" class="form-control" list="list-books" id="exampleDataList" placeholder="Type to search..." asp-for="InputModel.Book">
                }
               
                <datalist id="list-books">
                    @if (Model.Books.Count() > 0)
                    {
                        foreach (var book in Model.Books)
                        {
                            <option value="@book.Title" />
                        }
                    }
                </datalist>
                <span asp-validation-for="InputModel.Book" class="text-danger"></span>
            </div>
            <div class="d-flex gap-3 justify-content-center">
                <a asp-page="./Index" class="px-5 rounded-pill btn btn-outline-primary">
                    Cancel
                </a>
                <button class="btn btn-primary px-5 rounded-pill">Borrow</button>
            </div>
        </form>
    </div>
</div>
@section Scripts{
    <partial name="PartialViews/_ValidationScriptsPartial" />
    <script>
        $("#category").on("change", function () {
            $("#form-filter").submit();
        })
    </script>
}

LibraryManagement/Pages/Application/UserArea/Index.cshtml
@page
@model LibraryManagement.Pages.StudentArea.IndexModel
@{ 
     ViewData["Title"] = "User Area";
}
<partial name="PartialViews/_ValidationMessage"/>
<partial name="_UserLogForm" model="new InputUserAttendanceModel()"/>
<vc:navigation current-page="StudentArea"/>
<div class="mb-4">
    <form id="borrow-scan-form" asp-page-handler="BarrowScan" method="post">
        <input type="hidden" asp-for="UserId" id="user-barrow-id" />
    </form>
    <button @(Model.Books == 0 ? "disabled aria-disabled='true'" : "") id="barrow-btn" data-bs-toggle="modal" data-bs-target="#barrow-modal-qr" class="btn btn-primary px-5 rounded-pill py-2 border border-2 border-primary">
        Borrow <i class="fa-solid fa-book"></i>
    </button>
    <div class="modal fade" data-bs-backdrop="static" id="barrow-modal-qr">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>Scan QR-Code</h5>
                    <button id="exit-barrow-btn" class="btn-close" type="button" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <div class="mt-4 mb-4 overflow-hidden rounded border border-1 px-2 w-100" style="height: 200px;">
                        <video id="barrow-scan" class="object-fit-cover w-100 h-100">
                        </video>
                    </div>
                    <form asp-page-handler="BarrowScan" method="post">
                        <div class="mb-3">
                            <input class="form-control mb-2" placeholder="Enter id" asp-for="UserId"/>
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
</div>
<div class="row">
    <div class="col-4">
        <div class="shadow rounded overflow-hidden bg-white position-sticky" style="top: 100px">
            <div class="py-1 bg-primary"></div>
            <div class="px-3 pt-2" >
                <span class="fs-4 mt-4"><i class="bi bi-webcam"></i> Webcam</span>
                <div id="allow-camera-text" class="d-none mt-4 mb-4 d-flex justify-content-center align-items-center px-2 w-100" style="height: 200px;">
                    <span><i class="bi bi-exclamation-circle"></i> <em>Make sure to allow access camera!!</em></span>
                </div>
                <div id="scanner-container" class="mt-4 mb-4 overflow-hidden rounded border border-1 px-2 w-100" style="height: 200px;">
                    <video id="log-scan" class=" object-fit-cover w-100 h-100">
                    </video>
                </div>
                <form method="post">
                    <div class="mb-3">
                        <input class="form-control mb-2" placeholder="Enter id" asp-for="InputModel.User" id="student-id" />
                        <input type="hidden" asp-for="InputModel.TimeIn" value="@DateTime.Now" />
                        <button type="submit" class="btn btn-primary w-100">Submit</button>
                    </div>
                </form>

                <button id="btn-close-camera" class="mb-4 btn-secondary w-100 btn btn-lg"><i class="bi bi-camera-video-off"></i> Stop Camera</button>
                <button id="btn-open-camera" class="d-none mb-4 btn-secondary w-100 btn btn-lg"><i class="bi bi-camera-video"></i> Open Camera</button>
            </div>
       </div>
    </div>
    <div class="col-8">
        <div class="rounded-4 shadow bg-white overflow-y-hidden mb-4">
            <span class="bg-primary text-white fw-bolder ps-3 py-3 fs-5 d-block">
               User Log Transaction Today
            </span>
            <div class="p-3">
                <table id="dataTable"
                       data-toggle="table"
                       data-search="true"
                       data-pagination="true"
                       data-side-pagination="client"
                       data-page-size="5"
                       data-page-list="[5,10,25,50,100,All]">
                    <thead>
                        <tr>
                            <th data-sortable="true">Name</th>
                            <th data-sortable="true">Type of user</th>
                            <th data-sortable="true">Time In</th>
                            <th data-sortable="true">Time Out</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @foreach(var userAttendance in Model.UsersAttendance)
                        {
                          
                            <tr>
                                <td>@userAttendance.User.FirstName @userAttendance.User.MiddleName @userAttendance.User.LastName</td>
                                <td>@userAttendance.User.UserType</td>
                                <td>@userAttendance.UserLog.TimeIn.ToString("hh:mm:ss tt")</td>
                                <td>
                                    @if(userAttendance.UserLog.TimeOut == null)
                                    {
                                    <span class="bg-secondary text-white px-2 py-1 rounded-3">
                                        still in the library
                                    </span>
                                    }
                                    else
                                    {
                                        @userAttendance.UserLog.TimeOut?.ToString("hh:mm:ss tt")
                                    }
                                </td>
                            </tr>    
                        }
                    </tbody>
                </table>
            </div>

        </div>
        <div class=" rounded-4 shadow bg-white overflow-y-hidden mb-4">
            <span class="bg-primary text-white fw-bolder ps-3 py-3 fs-5 d-block">
                Borrowed Books Transaction
                Today
            </span>
            <div class="p-3">
                <table id="dataTable"
                       data-toggle="table"
                       data-search="true"
                       data-pagination="true"
                       data-side-pagination="client"
                       data-page-size="5"
                       data-page-list="[5,10,25,50,100,All]">
                    <thead>
                        <tr>
                            <th data-sortable="true">Name</th>
                            <th data-sortable="true">Type Of User</th>
                            <th data-sortable="true">Book Title</th>
                            <th data-sortable="true">Borrow Time</th>
                            <th data-sortable="true">Returned Time</th>
                            <th>View</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        @foreach(var borBook in Model.BorrowedBooks)
                        {
                            <tr>
                                <td>@borBook.User.FirstName @borBook.User.MiddleName @borBook.User.LastName</td>
                                <td>@borBook.User.UserType</td>
                                <td>@borBook.Book.Title</td>
                                <td>@borBook.BorrowBook.BorrowTime.ToString("hh: mm:ss tt")</td>
                                <td>
                                    @if(borBook.BorrowBook.Returned != null)
                                    {
                                        <span> @borBook.BorrowBook.Returned?.ToString("hh: mm:ss tt")</span>
                                    }
                                    else
                                    {
                                        <a class="btn btn-warning rounded-3 text-white" asp-page-handler="BookReturn" asp-route-Id="@borBook.BorrowBook.Id">Set returned</a>
                                    }
                                </td>
                                <td>
                                    <i data-bs-target="#borrow-rec-view-@borBook.BorrowBook.Id" data-bs-toggle="modal" class="clickable text-success fs-5 fa-solid fa-eye"></i>
                                </td>
                            </tr>
                            <vc:view-borrow-book-record id="borBook.BorrowBook.Id"/>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <partial name="PartialViews/_ValidationScriptsPartial"/>
    <script src="~/js/ScannerScript.js" type="text/javascript" asp-append-version="true"></script>
    <script src="~/js/StudentArea.js" type="text/javascript" asp-append-version="true"></script>
}

LibraryManagement/Pages/Application/UserArea/_ModalBorrow.cshtml
@inject IBaseRepository<BookCategory> _bookCategoryRepo
@{
    var bookCategories = await _bookCategoryRepo.GetAllRecords();
}
@model string
<div class="modal fade" data-bs-backdrop="static" id="barrow-modal-qr">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5>Scan QR-Code</h5>
                <button id="exit-barrow-btn" class="btn-close" type="button" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mt-4 mb-4 overflow-hidden rounded border border-1 px-2 w-100" style="height: 200px;">
                    <video id="barrow-scan" class="object-fit-cover w-100 h-100">
                    </video>
                </div>
                <form asp-page-handler="BarrowScan" method="post">
                    <div class="mb-3">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

LibraryManagement/Pages/Application/UserArea/_UserLogForm.cshtml
@model InputUserAttendanceModel
<form id="form-log-scan" method="post">
    <input type="hidden" asp-for="User" id="student-id" />
    <input type="hidden" asp-for="TimeIn" value="@DateTime.Now" />
</form>