LibraryManagement/Pages/Application/AdminArea/AccountManagement/Index.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace LibraryManagement.Pages.Application.AdminArea.AccountManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IBaseRepository<IdentityUser> _accountRepo;
        public IndexModel(UserManager<IdentityUser> userManager,
                          IBaseRepository<IdentityUser> accountRepo,
                          SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _accountRepo = accountRepo;
            _signInManager = signInManager;
        }
        [BindProperty]
        public DeleteAccountInputModel DelAccInput { get; set; }
        public bool RequirePassword { get; set; }
        [BindProperty]
        public AddSubAdminAccountInputModel AddSubAdminInput { get; set; }
        public List<IdentityUser> Accounts { get; set; }

        public async Task OnGetAsync()
        {
            var accounts = await _accountRepo.GetAllRecords();
            Accounts = accounts.Where(x => x.UserName != User.Identity?.Name).ToList();
        }
        public async Task<IActionResult> OnPostAddAdmin()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var account = new IdentityUser()
            {
                EmailConfirmed = true,
                Email = AddSubAdminInput.Email,
                UserName = AddSubAdminInput.Email,
            };
            var create = await _userManager.CreateAsync(account, AddSubAdminInput.Password);
            if (!create.Succeeded)
            {

                TempData["ValidationMessage"] = "can't add this account (make sure that you used unique email)";
                return RedirectToPage();
            }
            TempData["ValidationMessage"] = "successfully added";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostDeleteAcc()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            RequirePassword = await _userManager.HasPasswordAsync(user);
            if (RequirePassword)
            {
                if (!await _userManager.CheckPasswordAsync(user, DelAccInput.Password))
                {
                    TempData["ValidationMessage"] = "incorrect password";
                    return RedirectToPage();
                }
            }

            var result = await _userManager.DeleteAsync(user);
            if (!result.Succeeded)
            {
                throw new InvalidOperationException($"Unexpected error occurred deleting user.");
            }
            await _signInManager.SignOutAsync();
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BestUser/Index.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BestUser
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IUserRepository _userRepo;
        public IndexModel(IUserRepository userRepo)
        {
            _userRepo = userRepo;
        }
        public List<BestUserModel> BestUsers { get; set; }
        public User TopOne { get; set; }
        public async Task OnGetAsync()
        {
            var rankingHolder = new List<BestUserModel>();
            var bestUsers = await _userRepo.BestUserRanking();
            var bestUserRank = bestUsers.ToList();
            var topTen = bestUserRank.Count()<=10?bestUserRank.Count():10;
            for(int x = 0; x < topTen; x++)
            {
                rankingHolder.Add(bestUserRank[x]);
            }
            BestUsers = rankingHolder;
            TopOne = await _userRepo.GetOneRecord(rankingHolder.First().UserId);
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BookCategoryManagement/CategoryManagement.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BookCategoryManagement
{
    public class CategoryManagementModel : AdminBasePageModel<BookCategory,InputBookCategoryModel>
    {

        private readonly IBookCategoryRepository _bookCategoryRepo;
        private readonly IMapper _mapper;
        public CategoryManagementModel(IMapper mapper,IBookCategoryRepository bookCategoryRepo):base(bookCategoryRepo,mapper)
        {
            _bookCategoryRepo= bookCategoryRepo;
            _mapper = mapper;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<BookCategory>(InputModel);
            await _bookCategoryRepo.Add(converted);
            validationMess = "successfully added";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostUpdate()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<BookCategory>(InputModel);
            await _bookCategoryRepo.Update(converted.Id,converted);
            validationMess = "successfully updated";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDeleteIntId(int Id)
        {
            if (Id < 0)
                return BadRequest(Id);
            await _bookCategoryRepo.Delete(Id);
            validationMess = "successfully deleted";
            return RedirectToPage();
        }

    }
}

LibraryManagement/Pages/Application/AdminArea/BookCategoryManagement/Index.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BookCategoryManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IBaseRepository<Book> _bookRepo;
        private readonly IBaseRepository<BookCategory> _bCateg;
        private readonly IMapper _mapper;
        public IndexModel(IBaseRepository<Book> bookRepo,IBaseRepository<BookCategory> bCateg,IMapper mapper)
        {
            _bookRepo = bookRepo;
            _bCateg = bCateg;
            _mapper = mapper;
        }


        public List<BookViewModel> Books { get; set; }

        [BindProperty]
        public InputBookModel InputBook { get; set; }
        public async Task OnGetAsync()
        {
            var books = await _bookRepo.GetAllRecords();
            var bCategs = await _bCateg.GetAllRecords();
            var recordBooks = bCategs
                .Join(books,
                bCat => bCat.Id,
                book => book.BookCategoryId,
                (bCat, book) => new BookViewModel
                {
                    Category = bCat,
                    Book = book
                }).ToList();
            Books =  recordBooks;
        }
        public async Task<IActionResult>OnPostAsync()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<Book>(InputBook);
            await _bookRepo.Add(converted);
            TempData["ValidationMessage"] = "successfully added";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostUpdate()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<Book>(InputBook);
            await _bookRepo.Update(converted.Id.ToString(),converted);
            TempData["ValidationMessage"] = "successfully updated";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnGetDeleteIntId(int Id)
        {
            if (Id < 0)
                return NotFound();
            await _bookRepo.Delete(Id.ToString());
            TempData["ValidationMessage"] = "successfully deleted";
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/BorrowedBookManagement/Index.cshtml.cs
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.BorrowedBookManagement
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IBorrowBookRepository _borBookRepo;
        public IndexModel(IBorrowBookRepository borBookRepo)
        {
            _borBookRepo = borBookRepo;
        }
        public List<BorrowedBooksViewModel> BorrowBookRecord { get; set; }
        public async Task OnGetAsync()
        {
            var borrowBooks = await _borBookRepo.BorrowBookList();
            BorrowBookRecord = borrowBooks.OrderByDescending(x => x.BorrowBook.Id).ToList();
        }
        public async Task<IActionResult> OnGetBookReturn(int Id)
        {
            var borBook = await _borBookRepo.GetOneRecord(Id);
            if (borBook == null)
                return BadRequest("invalid id");
            borBook.Returned = DateTime.Now;
            var result = borBook;
            await _borBookRepo.Update(Id, borBook);
            TempData["ValidationMessage"] = "successfully returned";
            return RedirectToPage();
        }
        public async Task<IActionResult> OnGetDeleteIntId(int Id)
        {
            if(Id<0)
                return NotFound();
            await _borBookRepo.Delete(Id);
            TempData["ValidationMessage"] = "successfully deleted";
            return RedirectToPage();
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/FacultyManagement.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;

namespace LibraryManagement.Pages.Application.AdminArea.UserManagement
{
    public class FacultyManagementModel: UserManagementBasePageModel<User,InputUserModel>
    {
        public FacultyManagementModel(IUserRepository userRepo, IMapper map) : base(userRepo, map)
        {
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/GuestManagement.cshtml.cs
using AutoMapper;
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryManagement.Pages.Application.AdminArea.UserManagement
{
    public class GuestManagementModel : UserManagementBasePageModel<User,InputUserModel>
    {
       public GuestManagementModel(IUserRepository repo,IMapper mapp):base(repo,mapp) { }
    }
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/UserRecordHistory.cshtml.cs
using LibraryManagement.Model.Domain;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace LibraryManagement.Pages.Application.AdminArea.StudentManagement
{
    [Authorize]
    public class UserRecordHistoryModel : PageModel
    {
        private readonly IUserRepository _userRepo;
        private readonly IUserAttendanceRepository _userAttRepo;
        private readonly IBorrowBookRepository _borBookRepo;
        public UserRecordHistoryModel(IUserRepository userRepo
            ,IUserAttendanceRepository userAttRepo,
            IBorrowBookRepository borBookRepo)
        {
            _userAttRepo = userAttRepo;
            _userRepo = userRepo;
            _borBookRepo = borBookRepo;
        }

        public User User { get; set; }
        public List<UserLog> LogHistory { get; set; }
        public List<BorrowedBooksViewModel> BorroweBookHistory { get; set; }
        public async Task<IActionResult> OnGetAsync(string Id)
        {
            var user = await _userRepo.GetOneRecord(Id);

            if (user == null)
                return BadRequest($"{Id} invalid Id");
          
            User = user;
            var userLogs = await _userAttRepo.GetAllRecords();
            var borrowedRecords = await _borBookRepo.BorrowBookList();
            BorroweBookHistory = borrowedRecords
                .Where(x => x.User.UserId == Id)
                .OrderByDescending(x => x.BorrowBook.BorrowTime)
                .ToList();
            LogHistory = userLogs
                .Where(x => x.User == Id)
                .OrderByDescending(x => x.Id)
                .ToList();
            return Page();
        }

        public async Task<IActionResult> OnGetDeleteLogin(int sId)
        {
            if (sId == 0)
                return BadRequest(sId);
           
            TempData["ValidationMessage"] = "successfully deleted";
            var userAttendance = await _userAttRepo.GetOne(sId);
            string Id = userAttendance?.User;
            await _userAttRepo.Delete(sId);
            return RedirectToPage("UserRecordHistory", new{ Id } );
        }
        public async Task<IActionResult>OnGetDeleteBorrow(int sId)
        {
            if (sId == 0)
                return BadRequest(sId);
           
            TempData["ValidationMessage"] = "successfully deleted";
            var borrowBook = await _borBookRepo.GetOneRecord(sId);
            string Id = borrowBook.UserId;
            await _borBookRepo.Delete(sId);
            return RedirectToPage("UserRecordHistory", new { Id });
        }
    }
}

LibraryManagement/Pages/ViewComponents/DashboardNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public class DashboardNavigationViewComponent: ViewComponent
    {
        public DashboardNavigationViewComponent() { }
        public async Task<IViewComponentResult> InvokeAsync(DNVModel model)
        {
            return View(model);
        }
    }
    public class DNVModel
    {
        public string PageName { get; set; }
        public (string linkName,string pageName,bool isCurrentPage)[] LinkName { get; set;}
    }
}

LibraryManagement/Pages/ViewComponents/QRCodeDownloadViewComponent.cs
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.Infrastracture.Services;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public class QRCodeDownloadViewComponent:ViewComponent
    {
        private readonly QRCode_Generator _qrGen;
        private readonly IUserRepository _userRepo;
        public QRCodeDownloadViewComponent(QRCode_Generator qrGen,IUserRepository userRepo)
        {
            _qrGen= qrGen;
            _userRepo= userRepo;
        }
        public async Task<IViewComponentResult>InvokeAsync(string Id)
        {
            var user = await _userRepo.GetOneRecord(Id);
            var qrCode = _qrGen.GenerateCode(Id.ToString());
            string imagebase64 = $"data:image/png;base64,{Convert.ToBase64String(qrCode)}";
            ViewData["qr-code"] = imagebase64;
            ViewData["filename"] = $"{user.FirstName}{user.LastName}_QR-Code";
            return View();
        }
    }
}

LibraryManagement/Pages/ViewComponents/UpdateUserViewComponent.cs
using AutoMapper;
using LibraryManagement.Model.Infrastracture.Contracts;
using LibraryManagement.Model.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;

namespace LibraryManagement.Pages.ViewComponents
{
    public class UpdateUserViewComponent: ViewComponent
    {
        private readonly IUserRepository _stRepository;
        private readonly IMapper _mapper;
        public UpdateUserViewComponent(IUserRepository stRepository, IMapper mapper)
        {
            _stRepository = stRepository;
            _mapper = mapper;
        }
        public async Task<IViewComponentResult> InvokeAsync(string Id)
        {
            var getStudent = await _stRepository.GetOneRecord(Id);
            var converted = _mapper.Map<InputUserModel>(getStudent);
            converted.LastUpdatedAt= DateTime.Now;
            return View(converted);
        }
    }
}

LibraryManagement/Pages/ViewComponents/UserNavigationViewComponent.cs
using LibraryManagement.Model.Domain;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagement.Pages.ViewComponents
{
    public class UserNavigationViewComponent: ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Users user)
        {
            return View(user);
        }
    }
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/UserRecordHistory.cshtml
@page
@model LibraryManagement.Pages.Application.AdminArea.StudentManagement.UserRecordHistoryModel
@{
    var bcVal = new DNVModel
            {
                PageName = "User",
                LinkName = new (string linkName, string pageName, bool isCurrentPage)[]
                      {
            ("/Application/AdminArea/Index","Dashboard",false),
             ("./Index","User Management",false),
            (null,"User Record",true)
                        }
            };
    ViewData["Title"] = "History";
}
<partial name="PartialViews/_ValidationMessage" />
<vc:dashboard-navigation model="bcVal" />
<div class="bg-white rounded-3 shadow p-4">
    <div class="row">
        <div class="col-5">
            <h5 class="mb-4 fw-bolder">Personal Information</h5>
            <hr class="mb-4 m-0 border-primary border border-opacity-50 border-2" />
            <div class="border-end" style="height: 500px">
                <div class="row">
                    <div class="col-5">
                        <div>
                            <img class="w-100 h-100 mb-3 rounded-3" src="~/image/@(Model.User.Gender == Gender.Male ? "MaleAvatar.png":"FemaleAvatar.png")" />
                            <button data-bs-toggle="modal" data-bs-target="#qrcode-download" class="btn btn-primary w-100">Show QR-Code <i class="fa-solid fa-qrcode"></i></button>
                            <vc:qr-code-download id="@Model.User.UserId" />
                        </div>
                       
                    </div>
                    <div class="col-6">
                       
                        <div class="d-flex flex-column gap-3">
                            <span class="fw-bolder">FullName: <span class="fw-lighter">@Model.User.FirstName @Model.User.MiddleName @Model.User.LastName</span></span>
                            <span class="fw-bolder">Id: <span class="fw-lighter">@Model.User.UserId</span></span>
                            <span class="fw-bolder">Gender: <span class="fw-lighter">@Model.User.Gender</span></span>
                            @if(Model.User.UserType == Users.Student)
                            {
                                <span class="fw-bolder">Course: <span class="fw-lighter">@Model.User.Course</span></span>
                            }
                            <span class="fw-bolder">Contact Number: <span class="fw-lighter">@Model.User.PhoneNumber</span></span>
                           
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-7">
            <h5 class="fw-bolder mb-4">Record History</h5>
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-loghistory" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Login History</button>
                    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-barrowedhistory" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Borrowed History</button>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-loghistory" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">
                    <table 
                           data-toggle="table"
                           data-search="true"
                           data-pagination="true"
                           data-side-pagination="client"
                           data-page-size="5"
                           data-page-list="[5,10,25,50,100,All]">
                        <thead>
                            <tr>
                                <th data-sortable="true">Date</th>
                                <th data-sortable="true">Time (In/Out)</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            @foreach(var log in Model.LogHistory)
                            {

                                <tr>
                                   
                                    <td>@log.TimeIn.ToString("yyy/MMM/dd")</td>
                                    <td>
                                        @log.TimeIn.ToString("hh:mmm tt") - @log.TimeOut?.ToString("hh:mmm tt")
                                    </td>
                                    <td>
                                        <button data-bs-target="#delete-login-@log.Id" data-bs-toggle="modal" class="p-0 m-0 bg-transparent border-0 text-danger">
                                            <i class="fa-solid fa-trash-can "></i>
                                        </button>
                                        <div class="modal fade" id="delete-login-@log.Id">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5>Delete Login</h5>
                                                        <button class="btn-close" data-bs-dismiss="modal"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Are you sure you want to delete this login record?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button data-bs-dismiss="modal" class="btn btn-light">Cancel</button>
                                                        <a class="btn btn-primary" asp-page-handler="DeleteLogin" asp-route-sId="@log.Id">Delete</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="nav-barrowedhistory" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
                    <table data-toggle="table"
                           data-search="true"
                           data-pagination="true"
                           data-side-pagination="client"
                           data-page-size="5"
                           data-page-list="[5,10,25,50,100,All]">
                        <thead>
                            <tr>

                                <th data-sortable="true">Book Name</th>
                                <th data-sortable="true">Barrowed Time</th>
                                <th data-sortable="true">Returned</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-group-divider">
                            @foreach(var borrow in Model.BorroweBookHistory)
                            {
                                <tr>
                                    <td class="text-nowrap">@borrow.Book.Title</td>
                                    <td>@borrow.BorrowBook.BorrowTime.ToString("hh:mm tt")</td>
                                    <td>@(borrow.BorrowBook.Returned != null ? borrow.BorrowBook.Returned?.ToString("hh:mm tt"):"not yet returned")</td>
                                    <td>

                                        <button data-bs-target="#delete-borrow-@borrow.BorrowBook.Id" data-bs-toggle="modal" class="p-0 m-0 bg-transparent border-0 text-danger">
                                            <i class="fa-solid fa-trash-can "></i>
                                        </button>
                                        <div class="modal fade" id="delete-borrow-@borrow.BorrowBook.Id">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5>Delete Login</h5>
                                                        <button class="btn-close" data-bs-dismiss="modal"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Are you sure you want to delete this login record?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button data-bs-dismiss="modal" class="btn btn-light">Cancel</button>
                                                        <a class="btn btn-primary" asp-page-handler="DeleteBorrow" asp-route-sId="@borrow.BorrowBook.Id">Delete</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <i data-bs-toggle="modal" data-bs-target="#borrow-rec-view-@borrow.BorrowBook.Id" class="clickable fa-solid fa-eye text-success"></i>
                                    </td>
                                </tr>
                                <vc:view-borrow-book-record Id="borrow.BorrowBook.Id"/>
                            }
                           
                        </tbody>
                    </table>
                </div>
               
            </div>
           
        </div>
    </div>
</div>

LibraryManagement/Pages/Application/AdminArea/UserManagement/UsersQRCode.cshtml
@page
@model LibraryManagement.Pages.Application.AdminArea.StudentManagement.StudentsQRCodeModel
@{
    var bcVal = new DNVModel
            {
                PageName = "User",
                LinkName = new (string linkName, string pageName, bool isCurrentPage)[]
                        {
            ("/Application/AdminArea/Index","Dashboard",false),
            ("./Index","Student Management",false),
            (null,"Students QR-Code",true)
                        }
            };
    ViewData["Title"] = "QR-Codes";
}
<vc:dashboard-navigation model="bcVal" />
<partial name="PartialViews/_ValidationMessage" />
<div class="d-flex justify-content-end align-items-center gap-2 mb-2">
    <button id="btn-export-pdf" class="btn btn-info text-white rounded-3"><i class="fa-regular fa-file-pdf"></i></button>
</div>
<div class="bg-white rounded-3 shadow py-3 px-4">
    <div class="row" id="qr-codes">
        @foreach(var qrcode in Model.QRCodes)
        {
            <div class="col-3 border border-1">
                <div class="py-3 px-2 d-flex flex-column gap-2 justify-content-center align-items-center">
                    <img src="@qrcode.QRCode" width="150" height="150" />
                    <span class="text-center d-block">@qrcode.Name</span>
                    <span class="text-center d-block">@qrcode.Id</span>
                </div>
            </div>
        }
       
    </div>
</div>
@section Scripts{
    <script src="~/js/PrintQR-Codes.js"></script>
}

LibraryManagement/Pages/Application/AdminArea/UserManagement/_FormQR-Codes.cshtml
@using LibraryManagement.Model.Infrastracture.Contracts;
@model RecordSelectedInputModel
<form id="form-selected-ids" method="post" asp-page-handler="GenerateQRCode">
    <input id="selected-ids" type="hidden" asp-for="RecordIds" />
    <input type="hidden" asp-for="PageRoute" value="UsersQRCode"/>
</form>